Repository buza-project/buza-website, pull requests merged in 2018-08, with the labels that each got.

#33 Add new designs
  .coveragerc
  .env.example
  .gitignore
  Pipfile.lock
  README.rst
  package.json
  requirements-dev.txt
  requirements-old.txt
  setup.py
  src/buza/settings_base.py
  src/buza/settings_env.py
  src/buza/settings_env_dev.py
  src/buza/settings_tox.py
  src/buza/static/buza/css/questions.css
  src/buza/static/buza/css/site.css
  src/buza/static/buza/images/buza-logo.png
  src/buza/static/css/base_style.css
  src/buza/static/css/boards.css
  src/buza/static/css/fonts/DK-Cool-Crayon.ttf
  src/buza/static/css/fonts/Hanoded Fonts License & FAQ - DO READ.pdf
  src/buza/static/css/fonts/dk-cool-crayon.woff
  src/buza/templates/base.html
  src/buza/templates/buza/answer_form.html
  src/buza/templates/buza/my_subjects_list.html
  src/buza/templates/buza/question_detail.html
  src/buza/templates/buza/question_form.html
  src/buza/templates/buza/question_list.html
  src/buza/templates/buza/subject_detail.html
  src/buza/templates/buza/subject_list.html
  src/buza/templates/buza/user_detail.html
  src/buza/templates/includes/question_card_brief.html
  src/buza/templates/includes/question_card_full.html
  src/buza/views.py
  tests/test_settings_env.py
  tests/test_views.py
  yarn.lock
Labels: enhancement

#34 Update dependencies
  .travis.yml
  Pipfile.lock
  setup.py
  tox.ini
Labels: maintenance

#35 Wrangle Travis for Python 3.7
  .travis.yml
Labels: maintenance, small

#31 Add topics for questions
  src/buza/admin.py
  src/buza/migrations/0002_add_question_topics.py
  src/buza/models.py
  src/buza/settings_base.py
  src/buza/static/buza/css/questions.css
  src/buza/templates/base.html
  src/buza/templates/buza/question_detail.html
  src/buza/templates/buza/topic_detail.html
  src/buza/templates/includes/question_card_full.html
  src/buza/templatetags/buza_tags.py
  src/buza/urls.py
  src/buza/views.py
  tests/test_models.py
  tests/test_views.py
Labels: enhancement

#48 Settings: Remove unused buze_tags libraries declaration
  src/buza/settings_base.py
Labels: small
